src/Entity/Franchise.php
<?php
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\IdTrait;
use Doctrine\ORM\PersistentCollection;

/**
 * Class Franchise
 * @package App\Entity
 * @ORM\Entity()
 */
class Franchise
{
    use IdTrait;

    public function __construct()
    {
        $this->players = new ArrayCollection();
        $this->snapshots = new ArrayCollection();
    }

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @var Owner
     * @ORM\OneToOne(targetEntity="Owner", inversedBy="franchise")
     */
    private $owner;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $mflFranchiseId;

    /**
     * @var array
     * @ORM\Column(type="simple_array")
     */
    private $identifiers;

    /**
     * @var Collection|Player[]
     * @ORM\OneToMany(targetEntity="Player", mappedBy="franchise")
     */
    private $players;

    /**
     * @var ArrayCollection|PersistentCollection
     * @ORM\OneToMany(targetEntity="DraftPick", mappedBy="owner")
     */
    private $draftPicks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FranchiseSnapshot", mappedBy="franchise")
     * @ORM\OrderBy({"date" = "DESC"})
     */
    private $snapshots;

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return Owner
     */
    public function getOwner(): Owner
    {
        return $this->owner;
    }

    /**
     * @param Owner $owner
     */
    public function setOwner(Owner $owner): void
    {
        $this->owner = $owner;
    }

    /**
     * @return string
     */
    public function getMflFranchiseId(): string
    {
        return $this->mflFranchiseId;
    }

    /**
     * @param string $mflFranchiseId
     */
    public function setMflFranchiseId(string $mflFranchiseId): void
    {
        $this->mflFranchiseId = $mflFranchiseId;
    }

    /**
     * @return Collection|Player[]
     */
    public function getPlayers()
    {
        return $this->players;
    }

    /**
     * @return array
     */
    public function getIdentifiers(): array
    {
        return $this->identifiers;
    }

    /**
     * @param array $identifiers
     */
    public function setIdentifiers(array $identifiers): void
    {
        $this->identifiers = $identifiers;
    }

    public function __toString()
    {
        return $this->getName();
    }

    /**
     * @return Collection|FranchiseSnapshot[]
     */
    public function getSnapshots(): Collection
    {
        return $this->snapshots;
    }

    public function addSnapshot(FranchiseSnapshot $snapshot): self
    {
        if (!$this->snapshots->contains($snapshot)) {
            $this->snapshots[] = $snapshot;
            $snapshot->setFranchise($this);
        }

        return $this;
    }

    public function removeSnapshot(FranchiseSnapshot $snapshot): self
    {
        if ($this->snapshots->contains($snapshot)) {
            $this->snapshots->removeElement($snapshot);
            // set the owning side to null (unless already changed)
            if ($snapshot->getFranchise() === $this) {
                $snapshot->setFranchise(null);
            }
        }

        return $this;
    }

    public function getLatestSnapshot(): ?FranchiseSnapshot
    {
        return $this->snapshots[0];
    }
}

src/Controller/FranchiseController.php
<?php

namespace App\Controller;

use App\Entity\Franchise;
use App\Repository\FranchiseRepository;
use App\Repository\PlayerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class FranchiseController extends AbstractController
{
    /**
     * @var FranchiseRepository
     */
    private $franchiseRepository;

    public function __construct(FranchiseRepository $franchiseRepository)
    {
        $this->franchiseRepository = $franchiseRepository;
    }

    /**
     * @Route("/")
     */
    public function index()
    {
        $franchises = $this->franchiseRepository->findAllWithPlayers();

        return $this->render('franchise/index.html.twig', [
            'franchises' => $franchises,
        ]);
    }

    /**
     * @Route("/franchises/{id}")
     * @param Franchise $franchise
     * @param PlayerRepository $playerRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(Franchise $franchise, PlayerRepository $playerRepository)
    {
        return $this->render('franchise/show.html.twig', [
            'franchise' => $franchise,
            'roster' => $playerRepository->getPlayersForFranchiseOrdered($franchise),
        ]);
    }
}

templates/franchise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UK Dynasty{% endblock %}

{% block body %}
    <h2>Franchises</h2>

        {% for franchise in franchises %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ path('app_franchise_show', {'id': franchise.id}) }}">{{ franchise.name }}</a></h5>
                    <p class="card-text">{{ franchise.owner.name }}</p>
                    {% if franchise.latestSnapshot %}
                        <p>{{ franchise.latestSnapshot.bestLineupValue }} value best lineup</p>
                        {% include 'includes/_best-lineup.html.twig' with { players: franchise.latestSnapshot.bestLineup } %}
                    {% endif %}
                </div>
                <div class="card-footer text-muted">
                    {{ franchise.players.count() }} players
                </div>
            </div>
        {% endfor %}
{% endblock %}

templates/franchise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UK Dynasty{% endblock %}

{% block body %}
    <h2>{{ franchise.name }}</h2>
    <h3>Owner: {{ franchise.owner.name }}</h3>
    {% for player in roster %}
    <a href="{{ path('app_player_show', {id: player.id}) }}">{{ player.name }}</a> <strong>{{ player.position.name }}</strong> - {{ player.value }}<br>
    {% endfor %}
    <h4>Snapshots</h4>
    {% for snapshot in franchise.snapshots %}
        {{ snapshot.date | date }}: Best lineup {{ snapshot.bestLineupValue }} (average {{ snapshot.bestLineupValueAverage }}), Roster {{ snapshot.rosterValue }} (average {{ snapshot.rosterValueAverage }})<br>
    {% endfor %}
{% endblock %}